
service: scrum-vote

frameworkVersion: ">=1.9.0 <2.0.0"

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x
  websocketsApiName: custom-websockets-api-name
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    DDB_TABLE_SESSION: { Ref: SessionTable }
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:DescribeStream
      - dynamodb:GetRecords
      - dynamodb:GetShardIterator
      - dynamodb:ListStreams
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:Query
      - dynamodb:BatchWriteItem
      - dynamodb:UpdateItem
      Resource:
        - !GetAtt SessionTable.Arn
        - { "Fn::Join" : [ "/", [{ "Fn::GetAtt" : [SessionTable, Arn] }, "index/*"] ]}

custom:
  stage: ${opt:stage, self:provider.stage}
 

functions:
  connectHandler:
    handler: backend/handler.connectHandler
    events:
      - websocket:
          route: $connect
    
  disconnectHandler:
    handler: backend/handler.disconnectHandler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: backend/handler.defaultHandler
    events:
      - websocket:
          route: $default
  startSession:
    handler: backend/handler.startSessionHandler
    events:
      - http:
          cors: true
          path: /startSession
          method: post
  sessionStreamHandler:
    handler: backend/handler.handleStreamEvent
    events:
      - stream: {"Fn::GetAtt": [WebSite, WebsiteURL]}

resources:
  Outputs:
    WebSiteUrl:
      Value: {"Fn::GetAtt": [SessionTable, StreamArn]}
    WebSiteBucket:
      Value: {Ref: WebSite}
  Resources:
    WebSite:
        Type: "AWS::S3::Bucket"
        Properties:
          WebsiteConfiguration:
            ErrorDocument: index.html
            IndexDocument: index.html
    SessionTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          - IndexName: gsiConnectionToKeys
            KeySchema:
              - AttributeName: connectionId
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

package:
  exclude:
    - frontend/**
    - scripts/**
    - resources/**
    - package.json
    - package-lock.json
    - node_modules/**